/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminCreateRunner {
    #[serde(rename = "regionId")]
    pub region_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "apiKey")]
    pub api_key: String,
    /// The api version of the runner to create
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    /// The domain of the runner
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// The API URL of the runner
    #[serde(rename = "apiUrl", skip_serializing_if = "Option::is_none")]
    pub api_url: Option<String>,
    /// The proxy URL of the runner
    #[serde(rename = "proxyUrl", skip_serializing_if = "Option::is_none")]
    pub proxy_url: Option<String>,
    /// The CPU capacity of the runner
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<f64>,
    /// The memory capacity of the runner in GiB
    #[serde(rename = "memoryGiB", skip_serializing_if = "Option::is_none")]
    pub memory_gi_b: Option<f64>,
    /// The disk capacity of the runner in GiB
    #[serde(rename = "diskGiB", skip_serializing_if = "Option::is_none")]
    pub disk_gi_b: Option<f64>,
}

impl AdminCreateRunner {
    pub fn new(region_id: String, name: String, api_key: String, api_version: String) -> AdminCreateRunner {
        AdminCreateRunner {
            region_id,
            name,
            api_key,
            api_version,
            domain: None,
            api_url: None,
            proxy_url: None,
            cpu: None,
            memory_gi_b: None,
            disk_gi_b: None,
        }
    }
}

