/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyResponse {
    /// The name of the API key
    #[serde(rename = "name")]
    pub name: String,
    /// The API key value
    #[serde(rename = "value")]
    pub value: String,
    /// When the API key was created
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The list of organization resource permissions assigned to the API key
    #[serde(rename = "permissions")]
    pub permissions: Vec<Permissions>,
    /// When the API key expires
    #[serde(rename = "expiresAt", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<String>,
}

impl ApiKeyResponse {
    pub fn new(
        name: String,
        value: String,
        created_at: String,
        permissions: Vec<Permissions>,
        expires_at: Option<String>,
    ) -> ApiKeyResponse {
        ApiKeyResponse {
            name,
            value,
            created_at,
            permissions,
            expires_at,
        }
    }
}
/// The list of organization resource permissions assigned to the API key
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permissions {
    #[serde(rename = "write:registries")]
    WRITE_REGISTRIES,
    #[serde(rename = "delete:registries")]
    DELETE_REGISTRIES,
    #[serde(rename = "write:snapshots")]
    WRITE_SNAPSHOTS,
    #[serde(rename = "delete:snapshots")]
    DELETE_SNAPSHOTS,
    #[serde(rename = "write:sandboxes")]
    WRITE_SANDBOXES,
    #[serde(rename = "delete:sandboxes")]
    DELETE_SANDBOXES,
    #[serde(rename = "read:volumes")]
    READ_VOLUMES,
    #[serde(rename = "write:volumes")]
    WRITE_VOLUMES,
    #[serde(rename = "delete:volumes")]
    DELETE_VOLUMES,
    #[serde(rename = "write:regions")]
    WRITE_REGIONS,
    #[serde(rename = "delete:regions")]
    DELETE_REGIONS,
    #[serde(rename = "read:runners")]
    READ_RUNNERS,
    #[serde(rename = "write:runners")]
    WRITE_RUNNERS,
    #[serde(rename = "delete:runners")]
    DELETE_RUNNERS,
    #[serde(rename = "read:audit_logs")]
    READ_AUDIT_LOGS,
    #[serde(rename = "manage:api_keys")]
    MANAGE_API_KEYS,
    #[serde(rename = "manage:secrets")]
    MANAGE_SECRETS,
    #[serde(rename = "read:limits")]
    READ_LIMITS,
    #[serde(rename = "manage:sso")]
    MANAGE_SSO,
    #[serde(rename = "read:billing")]
    READ_BILLING,
    #[serde(rename = "manage:billing")]
    MANAGE_BILLING,
    #[serde(other)]
    UnknownDefaultOpenApi,
}

impl Default for Permissions {
    fn default() -> Permissions {
        Self::WRITE_REGISTRIES
    }
}
