/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyList {
    /// The name of the API key
    #[serde(rename = "name")]
    pub name: String,
    /// The masked API key value
    #[serde(rename = "value")]
    pub value: String,
    /// When the API key was created
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The list of organization resource permissions assigned to the API key
    #[serde(rename = "permissions")]
    pub permissions: Vec<Permissions>,
    /// When the API key was last used
    #[serde(rename = "lastUsedAt", deserialize_with = "Option::deserialize")]
    pub last_used_at: Option<String>,
    /// When the API key expires
    #[serde(rename = "expiresAt", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<String>,
    /// The user ID of the user who created the API key
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl ApiKeyList {
    pub fn new(name: String, value: String, created_at: String, permissions: Vec<Permissions>, last_used_at: Option<String>, expires_at: Option<String>, user_id: String) -> ApiKeyList {
        ApiKeyList {
            name,
            value,
            created_at,
            permissions,
            last_used_at,
            expires_at,
            user_id,
        }
    }
}
/// The list of organization resource permissions assigned to the API key
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permissions {
    #[serde(rename = "write:registries")]
    WriteColonRegistries,
    #[serde(rename = "delete:registries")]
    DeleteColonRegistries,
    #[serde(rename = "write:snapshots")]
    WriteColonSnapshots,
    #[serde(rename = "delete:snapshots")]
    DeleteColonSnapshots,
    #[serde(rename = "write:sandboxes")]
    WriteColonSandboxes,
    #[serde(rename = "delete:sandboxes")]
    DeleteColonSandboxes,
    #[serde(rename = "read:volumes")]
    ReadColonVolumes,
    #[serde(rename = "write:volumes")]
    WriteColonVolumes,
    #[serde(rename = "delete:volumes")]
    DeleteColonVolumes,
    #[serde(rename = "write:regions")]
    WriteColonRegions,
    #[serde(rename = "delete:regions")]
    DeleteColonRegions,
    #[serde(rename = "read:runners")]
    ReadColonRunners,
    #[serde(rename = "write:runners")]
    WriteColonRunners,
    #[serde(rename = "delete:runners")]
    DeleteColonRunners,
    #[serde(rename = "read:audit_logs")]
    ReadColonAuditLogs,
}

impl Default for Permissions {
    fn default() -> Permissions {
        Self::WriteColonRegistries
    }
}

