/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildInfo {
    /// The Dockerfile content used for the build
    #[serde(rename = "dockerfileContent", skip_serializing_if = "Option::is_none")]
    pub dockerfile_content: Option<String>,
    /// The context hashes used for the build
    #[serde(rename = "contextHashes", skip_serializing_if = "Option::is_none")]
    pub context_hashes: Option<Vec<String>>,
    /// The creation timestamp
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The last update timestamp
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// The snapshot reference
    #[serde(rename = "snapshotRef")]
    pub snapshot_ref: String,
}

impl BuildInfo {
    pub fn new(created_at: String, updated_at: String, snapshot_ref: String) -> BuildInfo {
        BuildInfo {
            dockerfile_content: None,
            context_hashes: None,
            created_at,
            updated_at,
            snapshot_ref,
        }
    }
}

