/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputerUseStartResponse {
    /// A message indicating the result of starting computer use processes
    #[serde(rename = "message")]
    pub message: String,
    /// Status information about all VNC desktop processes after starting
    #[serde(rename = "status")]
    pub status: serde_json::Value,
}

impl ComputerUseStartResponse {
    pub fn new(message: String, status: serde_json::Value) -> ComputerUseStartResponse {
        ComputerUseStartResponse {
            message,
            status,
        }
    }
}

