/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputerUseStatusResponse {
    /// Status of computer use services (active, partial, inactive, error)
    #[serde(rename = "status")]
    pub status: Status,
}

impl ComputerUseStatusResponse {
    pub fn new(status: Status) -> ComputerUseStatusResponse {
        ComputerUseStatusResponse {
            status,
        }
    }
}
/// Status of computer use services (active, partial, inactive, error)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "partial")]
    Partial,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "error")]
    Error,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

