/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWarmPool {
    /// The snapshot (id or name) to keep warm sandboxes for. A pool only serves sandbox creates that use this snapshot with the default OS user and no custom env, volumes or secrets.
    #[serde(rename = "snapshot")]
    pub snapshot: String,
    /// Number of warm sandboxes to keep ready (capped by the organization quota)
    #[serde(rename = "pool")]
    pub pool: f64,
    /// Target region for the warm pool. Defaults to the organization default region.
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
}

impl CreateWarmPool {
    pub fn new(snapshot: String, pool: f64) -> CreateWarmPool {
        CreateWarmPool {
            snapshot,
            pool,
            target: None,
        }
    }
}
