/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSnapshot {
    /// The name of the snapshot
    #[serde(rename = "name")]
    pub name: String,
    /// The image name of the snapshot
    #[serde(rename = "imageName", skip_serializing_if = "Option::is_none")]
    pub image_name: Option<String>,
    /// The entrypoint command for the snapshot
    #[serde(rename = "entrypoint", skip_serializing_if = "Option::is_none")]
    pub entrypoint: Option<Vec<String>>,
    /// CPU cores allocated to the resulting sandbox
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<i32>,
    /// GPU units allocated to the resulting sandbox
    #[serde(rename = "gpu", skip_serializing_if = "Option::is_none")]
    pub gpu: Option<i32>,
    /// Preferred GPU type for the resulting sandbox.
    #[serde(rename = "gpuType", skip_serializing_if = "Option::is_none")]
    pub gpu_type: Option<Vec<models::GpuType>>,
    /// Memory allocated to the resulting sandbox in GB
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<i32>,
    /// Disk space allocated to the sandbox in GB
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<i32>,
    /// Build information for the snapshot
    #[serde(rename = "buildInfo", skip_serializing_if = "Option::is_none")]
    pub build_info: Option<Box<models::CreateBuildInfo>>,
    /// ID of the region where the snapshot will be available. Defaults to organization default region if not specified.
    #[serde(rename = "regionId", skip_serializing_if = "Option::is_none")]
    pub region_id: Option<String>,
    /// Target sandbox class. Determines which runners can host sandboxes created from this snapshot.
    #[serde(rename = "sandboxClass", skip_serializing_if = "Option::is_none")]
    pub sandbox_class: Option<models::SandboxClass>,
}

impl CreateSnapshot {
    pub fn new(name: String) -> CreateSnapshot {
        CreateSnapshot {
            name,
            image_name: None,
            entrypoint: None,
            cpu: None,
            gpu: None,
            gpu_type: None,
            memory: None,
            disk: None,
            build_info: None,
            region_id: None,
            sandbox_class: None,
        }
    }
}
