/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRegionResponse {
    /// ID of the created region
    #[serde(rename = "id")]
    pub id: String,
    /// Proxy API key for the region
    #[serde(rename = "proxyApiKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub proxy_api_key: Option<Option<String>>,
    /// SSH Gateway API key for the region
    #[serde(rename = "sshGatewayApiKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ssh_gateway_api_key: Option<Option<String>>,
    /// Snapshot Manager username for the region
    #[serde(rename = "snapshotManagerUsername", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub snapshot_manager_username: Option<Option<String>>,
    /// Snapshot Manager password for the region
    #[serde(rename = "snapshotManagerPassword", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub snapshot_manager_password: Option<Option<String>>,
}

impl CreateRegionResponse {
    pub fn new(id: String) -> CreateRegionResponse {
        CreateRegionResponse {
            id,
            proxy_api_key: None,
            ssh_gateway_api_key: None,
            snapshot_manager_username: None,
            snapshot_manager_password: None,
        }
    }
}

