/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DockerRegistry {
    /// Registry ID
    #[serde(rename = "id")]
    pub id: String,
    /// Registry name
    #[serde(rename = "name")]
    pub name: String,
    /// Registry URL
    #[serde(rename = "url")]
    pub url: String,
    /// Registry username
    #[serde(rename = "username")]
    pub username: String,
    /// Registry project
    #[serde(rename = "project")]
    pub project: String,
    /// Registry type
    #[serde(rename = "registryType")]
    pub registry_type: RegistryType,
    /// Creation timestamp
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Last update timestamp
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl DockerRegistry {
    pub fn new(id: String, name: String, url: String, username: String, project: String, registry_type: RegistryType, created_at: String, updated_at: String) -> DockerRegistry {
        DockerRegistry {
            id,
            name,
            url,
            username,
            project,
            registry_type,
            created_at,
            updated_at,
        }
    }
}
/// Registry type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegistryType {
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "organization")]
    Organization,
    #[serde(rename = "transient")]
    Transient,
    #[serde(rename = "backup")]
    Backup,
}

impl Default for RegistryType {
    fn default() -> RegistryType {
        Self::Internal
    }
}

