/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadFiles {
    /// List of remote file paths to download
    #[serde(rename = "paths")]
    pub paths: Vec<String>,
}

impl DownloadFiles {
    pub fn new(paths: Vec<String>) -> DownloadFiles {
        DownloadFiles {
            paths,
        }
    }
}

