/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecuteRequest {
    #[serde(rename = "command")]
    pub command: String,
    /// Current working directory
    #[serde(rename = "cwd", skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// Timeout in seconds, defaults to 10 seconds
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<f64>,
}

impl ExecuteRequest {
    pub fn new(command: String) -> ExecuteRequest {
        ExecuteRequest {
            command,
            cwd: None,
            timeout: None,
        }
    }
}

