/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyboardHotkeyRequest {
    /// The hotkey combination to press (e.g., \"ctrl+c\", \"cmd+v\", \"alt+tab\")
    #[serde(rename = "keys")]
    pub keys: String,
}

impl KeyboardHotkeyRequest {
    pub fn new(keys: String) -> KeyboardHotkeyRequest {
        KeyboardHotkeyRequest {
            keys,
        }
    }
}

