/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyboardPressRequest {
    /// The key to press (e.g., a, b, c, enter, space, etc.)
    #[serde(rename = "key")]
    pub key: String,
    /// Array of modifier keys to press along with the main key (ctrl, alt, shift, cmd)
    #[serde(rename = "modifiers", skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<Vec<String>>,
}

impl KeyboardPressRequest {
    pub fn new(key: String) -> KeyboardPressRequest {
        KeyboardPressRequest {
            key,
            modifiers: None,
        }
    }
}

