/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSecretsResponse {
    /// List of results for the current page
    #[serde(rename = "items")]
    pub items: Vec<models::Secret>,
    /// Total number of secrets matching the filters
    #[serde(rename = "total")]
    pub total: f64,
    /// Cursor for the next page of results
    #[serde(rename = "nextCursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
}

impl ListSecretsResponse {
    pub fn new(
        items: Vec<models::Secret>,
        total: f64,
        next_cursor: Option<String>,
    ) -> ListSecretsResponse {
        ListSecretsResponse {
            items,
            total,
            next_cursor,
        }
    }
}
