/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSandboxesResponse {
    /// List of results for the current page
    #[serde(rename = "items")]
    pub items: Vec<models::SandboxListItem>,
    /// Cursor for the next page of results
    #[serde(rename = "nextCursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
}

impl ListSandboxesResponse {
    pub fn new(
        items: Vec<models::SandboxListItem>,
        next_cursor: Option<String>,
    ) -> ListSandboxesResponse {
        ListSandboxesResponse { items, next_cursor }
    }
}
