/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBranchResponse {
    #[serde(rename = "branches")]
    pub branches: Vec<String>,
}

impl ListBranchResponse {
    pub fn new(branches: Vec<String>) -> ListBranchResponse {
        ListBranchResponse {
            branches,
        }
    }
}

