/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogEntry {
    /// Timestamp of the log entry
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Log message body
    #[serde(rename = "body")]
    pub body: String,
    /// Severity level text (e.g., INFO, WARN, ERROR)
    #[serde(rename = "severityText")]
    pub severity_text: String,
    /// Severity level number
    #[serde(rename = "severityNumber", skip_serializing_if = "Option::is_none")]
    pub severity_number: Option<f64>,
    /// Service name that generated the log
    #[serde(rename = "serviceName")]
    pub service_name: String,
    /// Resource attributes from OTEL
    #[serde(rename = "resourceAttributes")]
    pub resource_attributes: std::collections::HashMap<String, String>,
    /// Log-specific attributes
    #[serde(rename = "logAttributes")]
    pub log_attributes: std::collections::HashMap<String, String>,
    /// Associated trace ID if available
    #[serde(rename = "traceId", skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    /// Associated span ID if available
    #[serde(rename = "spanId", skip_serializing_if = "Option::is_none")]
    pub span_id: Option<String>,
}

impl LogEntry {
    pub fn new(timestamp: String, body: String, severity_text: String, service_name: String, resource_attributes: std::collections::HashMap<String, String>, log_attributes: std::collections::HashMap<String, String>) -> LogEntry {
        LogEntry {
            timestamp,
            body,
            severity_text,
            severity_number: None,
            service_name,
            resource_attributes,
            log_attributes,
            trace_id: None,
            span_id: None,
        }
    }
}

