/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspCompletionParams {
    /// Language identifier
    #[serde(rename = "languageId")]
    pub language_id: String,
    /// Path to the project
    #[serde(rename = "pathToProject")]
    pub path_to_project: String,
    /// Document URI
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "position")]
    pub position: Box<models::Position>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::CompletionContext>>,
}

impl LspCompletionParams {
    pub fn new(language_id: String, path_to_project: String, uri: String, position: models::Position) -> LspCompletionParams {
        LspCompletionParams {
            language_id,
            path_to_project,
            uri,
            position: Box::new(position),
            context: None,
        }
    }
}

