/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspSymbol {
    #[serde(rename = "kind")]
    pub kind: f64,
    #[serde(rename = "location")]
    pub location: Box<models::LspLocation>,
    #[serde(rename = "name")]
    pub name: String,
}

impl LspSymbol {
    pub fn new(kind: f64, location: models::LspLocation, name: String) -> LspSymbol {
        LspSymbol {
            kind,
            location: Box::new(location),
            name,
        }
    }
}

