/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspDocumentRequest {
    /// Language identifier
    #[serde(rename = "languageId")]
    pub language_id: String,
    /// Path to the project
    #[serde(rename = "pathToProject")]
    pub path_to_project: String,
    /// Document URI
    #[serde(rename = "uri")]
    pub uri: String,
}

impl LspDocumentRequest {
    pub fn new(language_id: String, path_to_project: String, uri: String) -> LspDocumentRequest {
        LspDocumentRequest {
            language_id,
            path_to_project,
            uri,
        }
    }
}

