/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MouseScrollResponse {
    /// Whether the mouse scroll operation was successful
    #[serde(rename = "success")]
    pub success: bool,
}

impl MouseScrollResponse {
    pub fn new(success: bool) -> MouseScrollResponse {
        MouseScrollResponse {
            success,
        }
    }
}

