/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MouseMoveResponse {
    /// The actual X coordinate where the mouse cursor ended up
    #[serde(rename = "x")]
    pub x: f64,
    /// The actual Y coordinate where the mouse cursor ended up
    #[serde(rename = "y")]
    pub y: f64,
}

impl MouseMoveResponse {
    pub fn new(x: f64, y: f64) -> MouseMoveResponse {
        MouseMoveResponse {
            x,
            y,
        }
    }
}

