/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationSandboxDefaultLimitedNetworkEgress {
    /// Sandbox default limited network egress
    #[serde(rename = "sandboxDefaultLimitedNetworkEgress")]
    pub sandbox_default_limited_network_egress: bool,
}

impl OrganizationSandboxDefaultLimitedNetworkEgress {
    pub fn new(sandbox_default_limited_network_egress: bool) -> OrganizationSandboxDefaultLimitedNetworkEgress {
        OrganizationSandboxDefaultLimitedNetworkEgress {
            sandbox_default_limited_network_egress,
        }
    }
}

