/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationRole {
    /// Role ID
    #[serde(rename = "id")]
    pub id: String,
    /// Role name
    #[serde(rename = "name")]
    pub name: String,
    /// Role description
    #[serde(rename = "description")]
    pub description: String,
    /// Roles assigned to the user
    #[serde(rename = "permissions")]
    pub permissions: Vec<Permissions>,
    /// Global role flag
    #[serde(rename = "isGlobal")]
    pub is_global: bool,
    /// Creation timestamp
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Last update timestamp
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl OrganizationRole {
    pub fn new(id: String, name: String, description: String, permissions: Vec<Permissions>, is_global: bool, created_at: String, updated_at: String) -> OrganizationRole {
        OrganizationRole {
            id,
            name,
            description,
            permissions,
            is_global,
            created_at,
            updated_at,
        }
    }
}
/// Roles assigned to the user
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permissions {
    #[serde(rename = "write:registries")]
    WriteColonRegistries,
    #[serde(rename = "delete:registries")]
    DeleteColonRegistries,
    #[serde(rename = "write:snapshots")]
    WriteColonSnapshots,
    #[serde(rename = "delete:snapshots")]
    DeleteColonSnapshots,
    #[serde(rename = "write:sandboxes")]
    WriteColonSandboxes,
    #[serde(rename = "delete:sandboxes")]
    DeleteColonSandboxes,
    #[serde(rename = "read:volumes")]
    ReadColonVolumes,
    #[serde(rename = "write:volumes")]
    WriteColonVolumes,
    #[serde(rename = "delete:volumes")]
    DeleteColonVolumes,
    #[serde(rename = "write:regions")]
    WriteColonRegions,
    #[serde(rename = "delete:regions")]
    DeleteColonRegions,
    #[serde(rename = "read:runners")]
    ReadColonRunners,
    #[serde(rename = "write:runners")]
    WriteColonRunners,
    #[serde(rename = "delete:runners")]
    DeleteColonRunners,
    #[serde(rename = "read:audit_logs")]
    ReadColonAuditLogs,
}

impl Default for Permissions {
    fn default() -> Permissions {
        Self::WriteColonRegistries
    }
}

