/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedSandboxes {
    #[serde(rename = "items")]
    pub items: Vec<models::Sandbox>,
    #[serde(rename = "total")]
    pub total: f64,
    #[serde(rename = "page")]
    pub page: f64,
    #[serde(rename = "totalPages")]
    pub total_pages: f64,
}

impl PaginatedSandboxes {
    pub fn new(items: Vec<models::Sandbox>, total: f64, page: f64, total_pages: f64) -> PaginatedSandboxes {
        PaginatedSandboxes {
            items,
            total,
            page,
            total_pages,
        }
    }
}

