/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessRestartResponse {
    /// A message indicating the result of restarting the process
    #[serde(rename = "message")]
    pub message: String,
    /// The name of the VNC process that was restarted
    #[serde(rename = "processName")]
    pub process_name: String,
}

impl ProcessRestartResponse {
    pub fn new(message: String, process_name: String) -> ProcessRestartResponse {
        ProcessRestartResponse {
            message,
            process_name,
        }
    }
}

