/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessStatusResponse {
    /// The name of the VNC process being checked
    #[serde(rename = "processName")]
    pub process_name: String,
    /// Whether the specified VNC process is currently running
    #[serde(rename = "running")]
    pub running: bool,
}

impl ProcessStatusResponse {
    pub fn new(process_name: String, running: bool) -> ProcessStatusResponse {
        ProcessStatusResponse {
            process_name,
            running,
        }
    }
}

