/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PtyCreateRequest {
    /// The unique identifier for the PTY session
    #[serde(rename = "id")]
    pub id: String,
    /// Starting directory for the PTY session, defaults to the sandbox's working directory
    #[serde(rename = "cwd", skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// Environment variables for the PTY session
    #[serde(rename = "envs", skip_serializing_if = "Option::is_none")]
    pub envs: Option<serde_json::Value>,
    /// Number of terminal columns
    #[serde(rename = "cols", skip_serializing_if = "Option::is_none")]
    pub cols: Option<f64>,
    /// Number of terminal rows
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<f64>,
    /// Whether to start the PTY session lazily (only start when first client connects)
    #[serde(rename = "lazyStart", skip_serializing_if = "Option::is_none")]
    pub lazy_start: Option<bool>,
}

impl PtyCreateRequest {
    pub fn new(id: String) -> PtyCreateRequest {
        PtyCreateRequest {
            id,
            cwd: None,
            envs: None,
            cols: None,
            rows: None,
            lazy_start: None,
        }
    }
}

