/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PtyCreateResponse {
    /// The unique identifier for the created PTY session
    #[serde(rename = "sessionId")]
    pub session_id: String,
}

impl PtyCreateResponse {
    pub fn new(session_id: String) -> PtyCreateResponse {
        PtyCreateResponse {
            session_id,
        }
    }
}

