/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PtyResizeRequest {
    /// Number of terminal columns
    #[serde(rename = "cols")]
    pub cols: f64,
    /// Number of terminal rows
    #[serde(rename = "rows")]
    pub rows: f64,
}

impl PtyResizeRequest {
    pub fn new(cols: f64, rows: f64) -> PtyResizeRequest {
        PtyResizeRequest {
            cols,
            rows,
        }
    }
}

