/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitEntry {
    /// Rate limit TTL in seconds
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<f64>,
    /// Rate limit max requests
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<f64>,
}

impl RateLimitEntry {
    pub fn new() -> RateLimitEntry {
        RateLimitEntry {
            ttl: None,
            limit: None,
        }
    }
}

