/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegenerateApiKeyResponse {
    /// The newly generated API key
    #[serde(rename = "apiKey")]
    pub api_key: String,
}

impl RegenerateApiKeyResponse {
    pub fn new(api_key: String) -> RegenerateApiKeyResponse {
        RegenerateApiKeyResponse {
            api_key,
        }
    }
}

