/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegionQuota {
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    #[serde(rename = "regionId")]
    pub region_id: String,
    #[serde(rename = "totalCpuQuota")]
    pub total_cpu_quota: f64,
    #[serde(rename = "totalMemoryQuota")]
    pub total_memory_quota: f64,
    #[serde(rename = "totalDiskQuota")]
    pub total_disk_quota: f64,
}

impl RegionQuota {
    pub fn new(organization_id: String, region_id: String, total_cpu_quota: f64, total_memory_quota: f64, total_disk_quota: f64) -> RegionQuota {
        RegionQuota {
            organization_id,
            region_id,
            total_cpu_quota,
            total_memory_quota,
            total_disk_quota,
        }
    }
}

