/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegionType : The type of the region
/// The type of the region
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegionType {
    #[serde(rename = "shared")]
    Shared,
    #[serde(rename = "dedicated")]
    Dedicated,
    #[serde(rename = "custom")]
    Custom,

}

impl std::fmt::Display for RegionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Shared => write!(f, "shared"),
            Self::Dedicated => write!(f, "dedicated"),
            Self::Custom => write!(f, "custom"),
        }
    }
}

impl Default for RegionType {
    fn default() -> RegionType {
        Self::Shared
    }
}

