/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegionUsageOverview {
    #[serde(rename = "regionId")]
    pub region_id: String,
    #[serde(rename = "totalCpuQuota")]
    pub total_cpu_quota: f64,
    #[serde(rename = "currentCpuUsage")]
    pub current_cpu_usage: f64,
    #[serde(rename = "totalMemoryQuota")]
    pub total_memory_quota: f64,
    #[serde(rename = "currentMemoryUsage")]
    pub current_memory_usage: f64,
    #[serde(rename = "totalDiskQuota")]
    pub total_disk_quota: f64,
    #[serde(rename = "currentDiskUsage")]
    pub current_disk_usage: f64,
}

impl RegionUsageOverview {
    pub fn new(region_id: String, total_cpu_quota: f64, current_cpu_usage: f64, total_memory_quota: f64, current_memory_usage: f64, total_disk_quota: f64, current_disk_usage: f64) -> RegionUsageOverview {
        RegionUsageOverview {
            region_id,
            total_cpu_quota,
            current_cpu_usage,
            total_memory_quota,
            current_memory_usage,
            total_disk_quota,
            current_disk_usage,
        }
    }
}

