/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceRequest {
    #[serde(rename = "files")]
    pub files: Vec<String>,
    #[serde(rename = "pattern")]
    pub pattern: String,
    #[serde(rename = "newValue")]
    pub new_value: String,
}

impl ReplaceRequest {
    pub fn new(files: Vec<String>, pattern: String, new_value: String) -> ReplaceRequest {
        ReplaceRequest {
            files,
            pattern,
            new_value,
        }
    }
}

