/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResizeSandbox {
    /// CPU cores to allocate to the sandbox (minimum: 1)
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<i32>,
    /// Memory in GB to allocate to the sandbox (minimum: 1)
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<i32>,
    /// Disk space in GB to allocate to the sandbox (can only be increased)
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<i32>,
}

impl ResizeSandbox {
    pub fn new() -> ResizeSandbox {
        ResizeSandbox {
            cpu: None,
            memory: None,
            disk: None,
        }
    }
}

