/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerServiceHealth {
    /// Name of the service being checked
    #[serde(rename = "serviceName")]
    pub service_name: String,
    /// Whether the service is healthy
    #[serde(rename = "healthy")]
    pub healthy: bool,
    /// Error reason if the service is unhealthy
    #[serde(rename = "errorReason", skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
}

impl RunnerServiceHealth {
    pub fn new(service_name: String, healthy: bool) -> RunnerServiceHealth {
        RunnerServiceHealth {
            service_name,
            healthy,
            error_reason: None,
        }
    }
}
