/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerHealthMetrics {
    /// Current CPU load average
    #[serde(rename = "currentCpuLoadAverage")]
    pub current_cpu_load_average: f64,
    /// Current CPU usage percentage
    #[serde(rename = "currentCpuUsagePercentage")]
    pub current_cpu_usage_percentage: f64,
    /// Current memory usage percentage
    #[serde(rename = "currentMemoryUsagePercentage")]
    pub current_memory_usage_percentage: f64,
    /// Current disk usage percentage
    #[serde(rename = "currentDiskUsagePercentage")]
    pub current_disk_usage_percentage: f64,
    /// Currently allocated CPU cores
    #[serde(rename = "currentAllocatedCpu")]
    pub current_allocated_cpu: f64,
    /// Currently allocated memory in GiB
    #[serde(rename = "currentAllocatedMemoryGiB")]
    pub current_allocated_memory_gi_b: f64,
    /// Currently allocated disk in GiB
    #[serde(rename = "currentAllocatedDiskGiB")]
    pub current_allocated_disk_gi_b: f64,
    /// Number of snapshots currently stored
    #[serde(rename = "currentSnapshotCount")]
    pub current_snapshot_count: f64,
    /// Number of started sandboxes
    #[serde(rename = "currentStartedSandboxes")]
    pub current_started_sandboxes: f64,
    /// Total CPU cores on the runner
    #[serde(rename = "cpu")]
    pub cpu: f64,
    /// Total RAM in GiB on the runner
    #[serde(rename = "memoryGiB")]
    pub memory_gi_b: f64,
    /// Total disk space in GiB on the runner
    #[serde(rename = "diskGiB")]
    pub disk_gi_b: f64,
}

impl RunnerHealthMetrics {
    pub fn new(current_cpu_load_average: f64, current_cpu_usage_percentage: f64, current_memory_usage_percentage: f64, current_disk_usage_percentage: f64, current_allocated_cpu: f64, current_allocated_memory_gi_b: f64, current_allocated_disk_gi_b: f64, current_snapshot_count: f64, current_started_sandboxes: f64, cpu: f64, memory_gi_b: f64, disk_gi_b: f64) -> RunnerHealthMetrics {
        RunnerHealthMetrics {
            current_cpu_load_average,
            current_cpu_usage_percentage,
            current_memory_usage_percentage,
            current_disk_usage_percentage,
            current_allocated_cpu,
            current_allocated_memory_gi_b,
            current_allocated_disk_gi_b,
            current_snapshot_count,
            current_started_sandboxes,
            cpu,
            memory_gi_b,
            disk_gi_b,
        }
    }
}

