/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerHealthcheck {
    /// Runner metrics
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Box<models::RunnerHealthMetrics>>,
    /// Health status of individual services on the runner
    #[serde(rename = "serviceHealth", skip_serializing_if = "Option::is_none")]
    pub service_health: Option<Vec<models::RunnerServiceHealth>>,
    /// Runner domain
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Runner proxy URL
    #[serde(rename = "proxyUrl", skip_serializing_if = "Option::is_none")]
    pub proxy_url: Option<String>,
    /// Runner API URL
    #[serde(rename = "apiUrl", skip_serializing_if = "Option::is_none")]
    pub api_url: Option<String>,
    /// Runner app version
    #[serde(rename = "appVersion")]
    pub app_version: String,
}

impl RunnerHealthcheck {
    pub fn new(app_version: String) -> RunnerHealthcheck {
        RunnerHealthcheck {
            metrics: None,
            service_health: None,
            domain: None,
            proxy_url: None,
            api_url: None,
            app_version,
        }
    }
}
