/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SandboxClass {
    #[serde(rename = "linux-vm")]
    LINUX_VM,
    #[serde(rename = "container")]
    CONTAINER,
    #[serde(rename = "android")]
    ANDROID,
    #[serde(rename = "windows")]
    WINDOWS,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl std::fmt::Display for SandboxClass {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LINUX_VM => write!(f, "linux-vm"),
            Self::CONTAINER => write!(f, "container"),
            Self::ANDROID => write!(f, "android"),
            Self::WINDOWS => write!(f, "windows"),
            Self::UnknownDefaultOpenApi => write!(f, "unknown_default_open_api"),
        }
    }
}

impl Default for SandboxClass {
    fn default() -> SandboxClass {
        Self::LINUX_VM
    }
}
