/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxLabels {
    /// Key-value pairs of labels
    #[serde(rename = "labels")]
    pub labels: std::collections::HashMap<String, String>,
}

impl SandboxLabels {
    pub fn new(labels: std::collections::HashMap<String, String>) -> SandboxLabels {
        SandboxLabels {
            labels,
        }
    }
}

