/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SandboxListSortDirection {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl std::fmt::Display for SandboxListSortDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Asc => write!(f, "asc"),
            Self::Desc => write!(f, "desc"),
            Self::UnknownDefaultOpenApi => write!(f, "unknown_default_open_api"),
        }
    }
}

impl Default for SandboxListSortDirection {
    fn default() -> SandboxListSortDirection {
        Self::Asc
    }
}
