/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxDesiredState : The desired state of the sandbox
/// The desired state of the sandbox
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SandboxDesiredState {
    #[serde(rename = "destroyed")]
    Destroyed,
    #[serde(rename = "started")]
    Started,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "resized")]
    Resized,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl std::fmt::Display for SandboxDesiredState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Destroyed => write!(f, "destroyed"),
            Self::Started => write!(f, "started"),
            Self::Stopped => write!(f, "stopped"),
            Self::Resized => write!(f, "resized"),
            Self::Archived => write!(f, "archived"),
            Self::Paused => write!(f, "paused"),
            Self::UnknownDefaultOpenApi => write!(f, "unknown_default_open_api"),
        }
    }
}

impl Default for SandboxDesiredState {
    fn default() -> SandboxDesiredState {
        Self::Destroyed
    }
}
