/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxInfo {
    /// The creation timestamp of the project
    #[serde(rename = "created")]
    pub created: String,
    /// Deprecated: The name of the sandbox
    #[serde(rename = "name")]
    pub name: String,
    /// Additional metadata provided by the provider
    #[serde(rename = "providerMetadata", skip_serializing_if = "Option::is_none")]
    pub provider_metadata: Option<String>,
}

impl SandboxInfo {
    pub fn new(created: String, name: String) -> SandboxInfo {
        SandboxInfo {
            created,
            name,
            provider_metadata: None,
        }
    }
}

