/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotResponse {
    /// Base64 encoded screenshot image data
    #[serde(rename = "screenshot")]
    pub screenshot: String,
    /// The current cursor position when the screenshot was taken
    #[serde(rename = "cursorPosition", skip_serializing_if = "Option::is_none")]
    pub cursor_position: Option<serde_json::Value>,
    /// The size of the screenshot data in bytes
    #[serde(rename = "sizeBytes", skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<f64>,
}

impl ScreenshotResponse {
    pub fn new(screenshot: String) -> ScreenshotResponse {
        ScreenshotResponse {
            screenshot,
            cursor_position: None,
            size_bytes: None,
        }
    }
}

