/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionExecuteRequest {
    /// The command to execute
    #[serde(rename = "command")]
    pub command: String,
    /// Whether to execute the command asynchronously
    #[serde(rename = "runAsync", skip_serializing_if = "Option::is_none")]
    pub run_async: Option<bool>,
    /// Deprecated: Use runAsync instead. Whether to execute the command asynchronously
    #[serde(rename = "async", skip_serializing_if = "Option::is_none")]
    pub r#async: Option<bool>,
}

impl SessionExecuteRequest {
    pub fn new(command: String) -> SessionExecuteRequest {
        SessionExecuteRequest {
            command,
            run_async: None,
            r#async: None,
        }
    }
}

