/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionExecuteResponse {
    /// The ID of the executed command
    #[serde(rename = "cmdId", skip_serializing_if = "Option::is_none")]
    pub cmd_id: Option<String>,
    /// The output of the executed command marked with stdout and stderr prefixes
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    /// The exit code of the executed command
    #[serde(rename = "exitCode", skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<f64>,
}

impl SessionExecuteResponse {
    pub fn new() -> SessionExecuteResponse {
        SessionExecuteResponse {
            cmd_id: None,
            output: None,
            exit_code: None,
        }
    }
}

