/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetSnapshotGeneralStatusDto {
    /// Whether the snapshot is general
    #[serde(rename = "general")]
    pub general: bool,
}

impl SetSnapshotGeneralStatusDto {
    pub fn new(general: bool) -> SetSnapshotGeneralStatusDto {
        SetSnapshotGeneralStatusDto {
            general,
        }
    }
}

