/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "organizationId", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<String>,
    #[serde(rename = "general")]
    pub general: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "imageName", skip_serializing_if = "Option::is_none")]
    pub image_name: Option<String>,
    #[serde(rename = "state")]
    pub state: models::SnapshotState,
    #[serde(rename = "size", deserialize_with = "Option::deserialize")]
    pub size: Option<f64>,
    #[serde(rename = "entrypoint", deserialize_with = "Option::deserialize")]
    pub entrypoint: Option<Vec<String>>,
    #[serde(rename = "cpu")]
    pub cpu: f64,
    #[serde(rename = "gpu")]
    pub gpu: f64,
    #[serde(rename = "mem")]
    pub mem: f64,
    #[serde(rename = "disk")]
    pub disk: f64,
    #[serde(rename = "errorReason", deserialize_with = "Option::deserialize")]
    pub error_reason: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastUsedAt", deserialize_with = "Option::deserialize")]
    pub last_used_at: Option<String>,
    /// Build information for the snapshot
    #[serde(rename = "buildInfo", skip_serializing_if = "Option::is_none")]
    pub build_info: Option<Box<models::BuildInfo>>,
    /// IDs of regions where the snapshot is available
    #[serde(rename = "regionIds", skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    /// The initial runner ID of the snapshot
    #[serde(rename = "initialRunnerId", skip_serializing_if = "Option::is_none")]
    pub initial_runner_id: Option<String>,
    /// The snapshot reference
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
}

impl SnapshotDto {
    pub fn new(id: String, general: bool, name: String, state: models::SnapshotState, size: Option<f64>, entrypoint: Option<Vec<String>>, cpu: f64, gpu: f64, mem: f64, disk: f64, error_reason: Option<String>, created_at: String, updated_at: String, last_used_at: Option<String>) -> SnapshotDto {
        SnapshotDto {
            id,
            organization_id: None,
            general,
            name,
            image_name: None,
            state,
            size,
            entrypoint,
            cpu,
            gpu,
            mem,
            disk,
            error_reason,
            created_at,
            updated_at,
            last_used_at,
            build_info: None,
            region_ids: None,
            initial_runner_id: None,
            r#ref: None,
        }
    }
}

