/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SnapshotState {
    #[serde(rename = "building")]
    Building,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "pulling")]
    Pulling,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "build_failed")]
    BuildFailed,
    #[serde(rename = "removing")]
    Removing,

}

impl std::fmt::Display for SnapshotState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Building => write!(f, "building"),
            Self::Pending => write!(f, "pending"),
            Self::Pulling => write!(f, "pulling"),
            Self::Active => write!(f, "active"),
            Self::Inactive => write!(f, "inactive"),
            Self::Error => write!(f, "error"),
            Self::BuildFailed => write!(f, "build_failed"),
            Self::Removing => write!(f, "removing"),
        }
    }
}

impl Default for SnapshotState {
    fn default() -> SnapshotState {
        Self::Building
    }
}

