/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageAccessDto {
    /// Access key for storage authentication
    #[serde(rename = "accessKey")]
    pub access_key: String,
    /// Secret key for storage authentication
    #[serde(rename = "secret")]
    pub secret: String,
    /// Session token for storage authentication
    #[serde(rename = "sessionToken")]
    pub session_token: String,
    /// Storage URL
    #[serde(rename = "storageUrl")]
    pub storage_url: String,
    /// Organization ID
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// S3 bucket name
    #[serde(rename = "bucket")]
    pub bucket: String,
}

impl StorageAccessDto {
    pub fn new(access_key: String, secret: String, session_token: String, storage_url: String, organization_id: String, bucket: String) -> StorageAccessDto {
        StorageAccessDto {
            access_key,
            secret,
            session_token,
            storage_url,
            organization_id,
            bucket,
        }
    }
}

