/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestIdentityProviderConnection {
    /// OIDC Issuer URL to test
    #[serde(rename = "issuerUrl")]
    pub issuer_url: String,
}

impl TestIdentityProviderConnection {
    pub fn new(issuer_url: String) -> TestIdentityProviderConnection {
        TestIdentityProviderConnection { issuer_url }
    }
}
