/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolboxProxyUrl {
    /// The toolbox proxy URL for the sandbox
    #[serde(rename = "url")]
    pub url: String,
}

impl ToolboxProxyUrl {
    pub fn new(url: String) -> ToolboxProxyUrl {
        ToolboxProxyUrl {
            url,
        }
    }
}

