/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TraceSpan {
    /// Trace identifier
    #[serde(rename = "traceId")]
    pub trace_id: String,
    /// Span identifier
    #[serde(rename = "spanId")]
    pub span_id: String,
    /// Parent span identifier
    #[serde(rename = "parentSpanId", skip_serializing_if = "Option::is_none")]
    pub parent_span_id: Option<String>,
    /// Span name
    #[serde(rename = "spanName")]
    pub span_name: String,
    /// Span start timestamp
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Span duration in nanoseconds
    #[serde(rename = "durationNs")]
    pub duration_ns: f64,
    /// Span attributes
    #[serde(rename = "spanAttributes")]
    pub span_attributes: std::collections::HashMap<String, String>,
    /// Status code of the span
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<String>,
    /// Status message
    #[serde(rename = "statusMessage", skip_serializing_if = "Option::is_none")]
    pub status_message: Option<String>,
}

impl TraceSpan {
    pub fn new(trace_id: String, span_id: String, span_name: String, timestamp: String, duration_ns: f64, span_attributes: std::collections::HashMap<String, String>) -> TraceSpan {
        TraceSpan {
            trace_id,
            span_id,
            parent_span_id: None,
            span_name,
            timestamp,
            duration_ns,
            span_attributes,
            status_code: None,
            status_message: None,
        }
    }
}

