/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOidcIdPConfig {
    /// OIDC Issuer URL
    #[serde(rename = "issuerUrl", skip_serializing_if = "Option::is_none")]
    pub issuer_url: Option<String>,
    /// OAuth Client ID
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// OAuth Client Secret
    #[serde(rename = "clientSecret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    /// OAuth scopes
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl UpdateOidcIdPConfig {
    pub fn new() -> UpdateOidcIdPConfig {
        UpdateOidcIdPConfig {
            issuer_url: None,
            client_id: None,
            client_secret: None,
            scope: None,
        }
    }
}
