/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrganizationRegionQuota {
    #[serde(rename = "sandboxClass", skip_serializing_if = "Option::is_none")]
    pub sandbox_class: Option<models::SandboxClass>,
    #[serde(rename = "totalCpuQuota", deserialize_with = "Option::deserialize")]
    pub total_cpu_quota: Option<f64>,
    #[serde(rename = "totalMemoryQuota", deserialize_with = "Option::deserialize")]
    pub total_memory_quota: Option<f64>,
    #[serde(rename = "totalDiskQuota", deserialize_with = "Option::deserialize")]
    pub total_disk_quota: Option<f64>,
    #[serde(rename = "totalGpuQuota", deserialize_with = "Option::deserialize")]
    pub total_gpu_quota: Option<f64>,
    #[serde(
        rename = "allowedGpuTypes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_gpu_types: Option<Option<Vec<models::GpuType>>>,
    #[serde(
        rename = "maxCpuPerSandbox",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_cpu_per_sandbox: Option<Option<f64>>,
    #[serde(
        rename = "maxMemoryPerSandbox",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_memory_per_sandbox: Option<Option<f64>>,
    #[serde(
        rename = "maxDiskPerSandbox",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_disk_per_sandbox: Option<Option<f64>>,
    #[serde(
        rename = "maxDiskPerNonEphemeralSandbox",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_disk_per_non_ephemeral_sandbox: Option<Option<f64>>,
    /// CPU maximum per requested GPU unit for GPU sandboxes.
    #[serde(
        rename = "maxCpuPerGpu",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_cpu_per_gpu: Option<Option<f64>>,
    /// Memory maximum per requested GPU unit for GPU sandboxes.
    #[serde(
        rename = "maxMemoryPerGpu",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_memory_per_gpu: Option<Option<f64>>,
    /// Disk maximum per requested GPU unit for GPU sandboxes.
    #[serde(
        rename = "maxDiskPerGpu",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_disk_per_gpu: Option<Option<f64>>,
    /// Maximum sandbox lifespan in minutes, measured from sandbox creation to its auto-destroy deadline. If null or 0, lifespan is unrestricted. When set, sandboxes created without a TTL default to this lifespan and TTL cannot be disabled.
    #[serde(
        rename = "maxSandboxLifespan",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_sandbox_lifespan: Option<Option<f64>>,
}

impl UpdateOrganizationRegionQuota {
    pub fn new(
        total_cpu_quota: Option<f64>,
        total_memory_quota: Option<f64>,
        total_disk_quota: Option<f64>,
        total_gpu_quota: Option<f64>,
    ) -> UpdateOrganizationRegionQuota {
        UpdateOrganizationRegionQuota {
            sandbox_class: None,
            total_cpu_quota,
            total_memory_quota,
            total_disk_quota,
            total_gpu_quota,
            allowed_gpu_types: None,
            max_cpu_per_sandbox: None,
            max_memory_per_sandbox: None,
            max_disk_per_sandbox: None,
            max_disk_per_non_ephemeral_sandbox: None,
            max_cpu_per_gpu: None,
            max_memory_per_gpu: None,
            max_disk_per_gpu: None,
            max_sandbox_lifespan: None,
        }
    }
}
