/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateLastActivity {
    /// Optional type of interaction that reset the activity timer.
    #[serde(rename = "activityType", skip_serializing_if = "Option::is_none")]
    pub activity_type: Option<String>,
}

impl UpdateLastActivity {
    pub fn new() -> UpdateLastActivity {
        UpdateLastActivity {
            activity_type: None,
        }
    }
}
