/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPublicKey {
    /// Public key
    #[serde(rename = "key")]
    pub key: String,
    /// Key name
    #[serde(rename = "name")]
    pub name: String,
}

impl UserPublicKey {
    pub fn new(key: String, name: String) -> UserPublicKey {
        UserPublicKey {
            key,
            name,
        }
    }
}

