/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookEvent : The type of event being sent
/// The type of event being sent
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookEvent {
    #[serde(rename = "sandbox.created")]
    SANDBOX_CREATED,
    #[serde(rename = "sandbox.state.updated")]
    SANDBOX_STATE_UPDATED,
    #[serde(rename = "snapshot.created")]
    SNAPSHOT_CREATED,
    #[serde(rename = "snapshot.state.updated")]
    SNAPSHOT_STATE_UPDATED,
    #[serde(rename = "snapshot.removed")]
    SNAPSHOT_REMOVED,
    #[serde(rename = "volume.created")]
    VOLUME_CREATED,
    #[serde(rename = "volume.state.updated")]
    VOLUME_STATE_UPDATED,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl std::fmt::Display for WebhookEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SANDBOX_CREATED => write!(f, "sandbox.created"),
            Self::SANDBOX_STATE_UPDATED => write!(f, "sandbox.state.updated"),
            Self::SNAPSHOT_CREATED => write!(f, "snapshot.created"),
            Self::SNAPSHOT_STATE_UPDATED => write!(f, "snapshot.state.updated"),
            Self::SNAPSHOT_REMOVED => write!(f, "snapshot.removed"),
            Self::VOLUME_CREATED => write!(f, "volume.created"),
            Self::VOLUME_STATE_UPDATED => write!(f, "volume.state.updated"),
            Self::UnknownDefaultOpenApi => write!(f, "unknown_default_open_api"),
        }
    }
}

impl Default for WebhookEvent {
    fn default() -> WebhookEvent {
        Self::SANDBOX_CREATED
    }
}
