/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspacePortPreviewUrl {
    /// Preview url
    #[serde(rename = "url")]
    pub url: String,
    /// Access token
    #[serde(rename = "token")]
    pub token: String,
}

impl WorkspacePortPreviewUrl {
    pub fn new(url: String, token: String) -> WorkspacePortPreviewUrl {
        WorkspacePortPreviewUrl {
            url,
            token,
        }
    }
}

