/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`admin_can_cleanup_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminCanCleanupImageError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_create_organization`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminCreateOrganizationError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_create_organization_region_quota`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminCreateOrganizationRegionQuotaError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_create_runner`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminCreateRunnerError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_create_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminCreateUserError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_delete_organization_region_quota`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminDeleteOrganizationRegionQuotaError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_delete_runner`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminDeleteRunnerError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_get_all_audit_logs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminGetAllAuditLogsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_get_message_attempts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminGetMessageAttemptsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_get_organization_region_quota`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminGetOrganizationRegionQuotaError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_get_runner_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminGetRunnerByIdError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_get_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminGetUserError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_get_webhook_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminGetWebhookStatusError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_initialize_webhooks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminInitializeWebhooksError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_list_runners`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminListRunnersError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_list_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminListUsersError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_recover_sandbox`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminRecoverSandboxError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_regenerate_key_pair`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminRegenerateKeyPairError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_send_webhook`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminSendWebhookError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_set_default_registry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminSetDefaultRegistryError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_set_snapshot_general_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminSetSnapshotGeneralStatusError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_update_organization_preview_warning`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminUpdateOrganizationPreviewWarningError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_update_organization_region_quota`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminUpdateOrganizationRegionQuotaError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`admin_update_runner_scheduling`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AdminUpdateRunnerSchedulingError {
    UnknownValue(serde_json::Value),
}

pub async fn admin_can_cleanup_image(
    configuration: &configuration::Configuration,
    image_name: &str,
) -> Result<bool, Error<AdminCanCleanupImageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_image_name = image_name;

    let uri_str = format!(
        "{}/admin/snapshots/can-cleanup-image",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("imageName", &p_query_image_name.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `bool`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `bool`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminCanCleanupImageError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_create_organization(
    configuration: &configuration::Configuration,
    admin_create_organization: models::AdminCreateOrganization,
) -> Result<models::Organization, Error<AdminCreateOrganizationError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_admin_create_organization = admin_create_organization;

    let uri_str = format!("{}/admin/organizations", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_admin_create_organization);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Organization`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Organization`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminCreateOrganizationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_create_organization_region_quota(
    configuration: &configuration::Configuration,
    organization_id: &str,
    region_id: &str,
    create_organization_region_quota: models::CreateOrganizationRegionQuota,
) -> Result<models::RegionQuota, Error<AdminCreateOrganizationRegionQuotaError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_path_region_id = region_id;
    let p_body_create_organization_region_quota = create_organization_region_quota;

    let uri_str = format!(
        "{}/admin/organizations/{organizationId}/quota/{regionId}",
        configuration.base_path,
        organizationId = crate::apis::urlencode(p_path_organization_id),
        regionId = crate::apis::urlencode(p_path_region_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_organization_region_quota);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RegionQuota`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RegionQuota`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminCreateOrganizationRegionQuotaError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_create_runner(
    configuration: &configuration::Configuration,
    admin_create_runner: models::AdminCreateRunner,
) -> Result<models::CreateRunnerResponse, Error<AdminCreateRunnerError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_admin_create_runner = admin_create_runner;

    let uri_str = format!("{}/admin/runners", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_admin_create_runner);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateRunnerResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateRunnerResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminCreateRunnerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_create_user(
    configuration: &configuration::Configuration,
    create_user: models::CreateUser,
) -> Result<(), Error<AdminCreateUserError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_user = create_user;

    let uri_str = format!("{}/admin/users", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_user);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminCreateUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_delete_organization_region_quota(
    configuration: &configuration::Configuration,
    organization_id: &str,
    region_id: &str,
    sandbox_class: models::SandboxClass,
) -> Result<(), Error<AdminDeleteOrganizationRegionQuotaError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_path_region_id = region_id;
    let p_path_sandbox_class = sandbox_class;

    let uri_str = format!(
        "{}/admin/organizations/{organizationId}/quota/{regionId}/{sandboxClass}",
        configuration.base_path,
        organizationId = crate::apis::urlencode(p_path_organization_id),
        regionId = crate::apis::urlencode(p_path_region_id),
        sandboxClass = p_path_sandbox_class.to_string()
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminDeleteOrganizationRegionQuotaError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_delete_runner(
    configuration: &configuration::Configuration,
    id: &str,
    force: Option<bool>,
) -> Result<(), Error<AdminDeleteRunnerError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_force = force;

    let uri_str = format!(
        "{}/admin/runners/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = p_query_force {
        req_builder = req_builder.query(&[("force", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminDeleteRunnerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_get_all_audit_logs(
    configuration: &configuration::Configuration,
    page: Option<f64>,
    limit: Option<f64>,
    from: Option<String>,
    to: Option<String>,
    next_token: Option<&str>,
    id: Option<models::StringFilter>,
    actor_id: Option<models::StringFilter>,
    actor_email: Option<models::StringFilter>,
    actor_api_key_prefix: Option<models::StringFilter>,
    actor_api_key_suffix: Option<models::StringFilter>,
    action: Option<models::StringFilter>,
    target_type: Option<models::StringFilter>,
    target_id: Option<models::StringFilter>,
    status_code: Option<models::IntFilter>,
    created_at: Option<models::DateFilter>,
) -> Result<models::PaginatedAuditLogs, Error<AdminGetAllAuditLogsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page = page;
    let p_query_limit = limit;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_next_token = next_token;
    let p_query_id = id;
    let p_query_actor_id = actor_id;
    let p_query_actor_email = actor_email;
    let p_query_actor_api_key_prefix = actor_api_key_prefix;
    let p_query_actor_api_key_suffix = actor_api_key_suffix;
    let p_query_action = action;
    let p_query_target_type = target_type;
    let p_query_target_id = target_id;
    let p_query_status_code = status_code;
    let p_query_created_at = created_at;

    let uri_str = format!("{}/admin/audit", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_next_token {
        req_builder = req_builder.query(&[("nextToken", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_actor_id {
        req_builder = req_builder.query(&[("actorId", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_actor_email {
        req_builder = req_builder.query(&[("actorEmail", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_actor_api_key_prefix {
        req_builder =
            req_builder.query(&[("actorApiKeyPrefix", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_actor_api_key_suffix {
        req_builder =
            req_builder.query(&[("actorApiKeySuffix", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_action {
        req_builder = req_builder.query(&[("action", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_target_type {
        req_builder = req_builder.query(&[("targetType", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_target_id {
        req_builder = req_builder.query(&[("targetId", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_status_code {
        req_builder = req_builder.query(&[("statusCode", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_created_at {
        req_builder = req_builder.query(&[("createdAt", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PaginatedAuditLogs`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PaginatedAuditLogs`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminGetAllAuditLogsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_get_message_attempts(
    configuration: &configuration::Configuration,
    organization_id: &str,
    message_id: &str,
) -> Result<Vec<serde_json::Value>, Error<AdminGetMessageAttemptsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_path_message_id = message_id;

    let uri_str = format!(
        "{}/admin/webhooks/organizations/{organizationId}/messages/{messageId}/attempts",
        configuration.base_path,
        organizationId = crate::apis::urlencode(p_path_organization_id),
        messageId = crate::apis::urlencode(p_path_message_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;serde_json::Value&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;serde_json::Value&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminGetMessageAttemptsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_get_organization_region_quota(
    configuration: &configuration::Configuration,
    organization_id: &str,
    region_id: &str,
    sandbox_class: models::SandboxClass,
) -> Result<models::RegionQuota, Error<AdminGetOrganizationRegionQuotaError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_path_region_id = region_id;
    let p_path_sandbox_class = sandbox_class;

    let uri_str = format!(
        "{}/admin/organizations/{organizationId}/quota/{regionId}/{sandboxClass}",
        configuration.base_path,
        organizationId = crate::apis::urlencode(p_path_organization_id),
        regionId = crate::apis::urlencode(p_path_region_id),
        sandboxClass = p_path_sandbox_class.to_string()
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RegionQuota`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RegionQuota`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminGetOrganizationRegionQuotaError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_get_runner_by_id(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<models::RunnerFull, Error<AdminGetRunnerByIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/admin/runners/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RunnerFull`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RunnerFull`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminGetRunnerByIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_get_user(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<models::User, Error<AdminGetUserError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/admin/users/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::User`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::User`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminGetUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_get_webhook_status(
    configuration: &configuration::Configuration,
) -> Result<models::AdminGetWebhookStatus200Response, Error<AdminGetWebhookStatusError>> {
    let uri_str = format!("{}/admin/webhooks/status", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AdminGetWebhookStatus200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AdminGetWebhookStatus200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminGetWebhookStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_initialize_webhooks(
    configuration: &configuration::Configuration,
    organization_id: &str,
) -> Result<(), Error<AdminInitializeWebhooksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;

    let uri_str = format!(
        "{}/admin/webhooks/organizations/{organizationId}/initialize",
        configuration.base_path,
        organizationId = crate::apis::urlencode(p_path_organization_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminInitializeWebhooksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_list_runners(
    configuration: &configuration::Configuration,
    region_id: Option<&str>,
) -> Result<Vec<models::RunnerFull>, Error<AdminListRunnersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_region_id = region_id;

    let uri_str = format!("{}/admin/runners", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_region_id {
        req_builder = req_builder.query(&[("regionId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::RunnerFull&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::RunnerFull&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminListRunnersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_list_users(
    configuration: &configuration::Configuration,
) -> Result<(), Error<AdminListUsersError>> {
    let uri_str = format!("{}/admin/users", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminListUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_recover_sandbox(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
) -> Result<models::Sandbox, Error<AdminRecoverSandboxError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_sandbox_id = sandbox_id;

    let uri_str = format!(
        "{}/admin/sandbox/{sandboxId}/recover",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_path_sandbox_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Sandbox`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Sandbox`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminRecoverSandboxError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_regenerate_key_pair(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<AdminRegenerateKeyPairError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/admin/users/{id}/regenerate-key-pair",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminRegenerateKeyPairError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_send_webhook(
    configuration: &configuration::Configuration,
    organization_id: &str,
    send_webhook_dto: models::SendWebhookDto,
) -> Result<(), Error<AdminSendWebhookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_body_send_webhook_dto = send_webhook_dto;

    let uri_str = format!(
        "{}/admin/webhooks/organizations/{organizationId}/send",
        configuration.base_path,
        organizationId = crate::apis::urlencode(p_path_organization_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_send_webhook_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminSendWebhookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_set_default_registry(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<models::DockerRegistry, Error<AdminSetDefaultRegistryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/admin/docker-registry/{id}/set-default",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DockerRegistry`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DockerRegistry`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminSetDefaultRegistryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_set_snapshot_general_status(
    configuration: &configuration::Configuration,
    id: &str,
    set_snapshot_general_status_dto: models::SetSnapshotGeneralStatusDto,
) -> Result<models::SnapshotDto, Error<AdminSetSnapshotGeneralStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_set_snapshot_general_status_dto = set_snapshot_general_status_dto;

    let uri_str = format!(
        "{}/admin/snapshots/{id}/general",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_set_snapshot_general_status_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SnapshotDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SnapshotDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminSetSnapshotGeneralStatusError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_update_organization_preview_warning(
    configuration: &configuration::Configuration,
    organization_id: &str,
    organization_preview_warning: models::OrganizationPreviewWarning,
) -> Result<(), Error<AdminUpdateOrganizationPreviewWarningError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_body_organization_preview_warning = organization_preview_warning;

    let uri_str = format!(
        "{}/admin/organizations/{organizationId}/preview-warning",
        configuration.base_path,
        organizationId = crate::apis::urlencode(p_path_organization_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_organization_preview_warning);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminUpdateOrganizationPreviewWarningError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_update_organization_region_quota(
    configuration: &configuration::Configuration,
    organization_id: &str,
    region_id: &str,
    update_organization_region_quota: models::UpdateOrganizationRegionQuota,
) -> Result<(), Error<AdminUpdateOrganizationRegionQuotaError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_path_region_id = region_id;
    let p_body_update_organization_region_quota = update_organization_region_quota;

    let uri_str = format!(
        "{}/admin/organizations/{organizationId}/quota/{regionId}",
        configuration.base_path,
        organizationId = crate::apis::urlencode(p_path_organization_id),
        regionId = crate::apis::urlencode(p_path_region_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_organization_region_quota);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminUpdateOrganizationRegionQuotaError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn admin_update_runner_scheduling(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<AdminUpdateRunnerSchedulingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/admin/runners/{id}/scheduling",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AdminUpdateRunnerSchedulingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
