/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Chart {
    #[serde(rename = "elements", skip_serializing_if = "Option::is_none")]
    pub elements: Option<Vec<models::ChartElement>>,
    #[serde(rename = "png", skip_serializing_if = "Option::is_none")]
    pub png: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "x_label", skip_serializing_if = "Option::is_none")]
    pub x_label: Option<String>,
    #[serde(rename = "x_scale", skip_serializing_if = "Option::is_none")]
    pub x_scale: Option<String>,
    #[serde(rename = "x_tick_labels", skip_serializing_if = "Option::is_none")]
    pub x_tick_labels: Option<Vec<String>>,
    #[serde(rename = "x_ticks", skip_serializing_if = "Option::is_none")]
    pub x_ticks: Option<Vec<f64>>,
    #[serde(rename = "y_label", skip_serializing_if = "Option::is_none")]
    pub y_label: Option<String>,
    #[serde(rename = "y_scale", skip_serializing_if = "Option::is_none")]
    pub y_scale: Option<String>,
    #[serde(rename = "y_tick_labels", skip_serializing_if = "Option::is_none")]
    pub y_tick_labels: Option<Vec<String>>,
    #[serde(rename = "y_ticks", skip_serializing_if = "Option::is_none")]
    pub y_ticks: Option<Vec<f64>>,
}

impl Chart {
    pub fn new() -> Chart {
        Chart {
            elements: None,
            png: None,
            title: None,
            r#type: None,
            x_label: None,
            x_scale: None,
            x_tick_labels: None,
            x_ticks: None,
            y_label: None,
            y_scale: None,
            y_tick_labels: None,
            y_ticks: None,
        }
    }
}
