/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeRunRequest {
    #[serde(rename = "argv", skip_serializing_if = "Option::is_none")]
    pub argv: Option<Vec<String>>,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "envs", skip_serializing_if = "Option::is_none")]
    pub envs: Option<std::collections::HashMap<String, String>>,
    /// python, javascript, typescript
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
}

impl CodeRunRequest {
    pub fn new(code: String, language: String) -> CodeRunRequest {
        CodeRunRequest {
            argv: None,
            code,
            envs: None,
            language,
            timeout: None,
        }
    }
}
