/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeRunArtifacts {
    #[serde(rename = "charts", skip_serializing_if = "Option::is_none")]
    pub charts: Option<Vec<models::Chart>>,
}

impl CodeRunArtifacts {
    pub fn new() -> CodeRunArtifacts {
        CodeRunArtifacts { charts: None }
    }
}
