/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionList {
    #[serde(rename = "isIncomplete")]
    pub is_incomplete: bool,
    #[serde(rename = "items")]
    pub items: Vec<models::CompletionItem>,
}

impl CompletionList {
    pub fn new(is_incomplete: bool, items: Vec<models::CompletionItem>) -> CompletionList {
        CompletionList {
            is_incomplete,
            items,
        }
    }
}

