/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequest {
    #[serde(rename = "sessionId")]
    pub session_id: String,
}

impl CreateSessionRequest {
    pub fn new(session_id: String) -> CreateSessionRequest {
        CreateSessionRequest {
            session_id,
        }
    }
}

