/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisplayInfoResponse {
    #[serde(rename = "displays", skip_serializing_if = "Option::is_none")]
    pub displays: Option<Vec<models::DisplayInfo>>,
}

impl DisplayInfoResponse {
    pub fn new() -> DisplayInfoResponse {
        DisplayInfoResponse {
            displays: None,
        }
    }
}

