/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileInfo {
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "isDir")]
    pub is_dir: bool,
    /// Deprecated: ModTime uses Go's time.String() layout which is not a standard format. Use ModifiedAt instead, which is serialized as ISO 8601 / RFC 3339.
    #[serde(rename = "modTime")]
    pub mod_time: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "modifiedAt")]
    pub modified_at: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "owner")]
    pub owner: String,
    /// Full path of the entry
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "permissions")]
    pub permissions: String,
    #[serde(rename = "size")]
    pub size: i64,
}

impl FileInfo {
    pub fn new(
        group: String,
        is_dir: bool,
        mod_time: String,
        mode: String,
        modified_at: String,
        name: String,
        owner: String,
        permissions: String,
        size: i64,
    ) -> FileInfo {
        FileInfo {
            group,
            is_dir,
            mod_time,
            mode,
            modified_at,
            name,
            owner,
            path: None,
            permissions,
            size,
        }
    }
}
