/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FindAccessibilityNodesRequest {
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// \"exact\" | \"substring\" | \"regex\"
    #[serde(rename = "nameMatch", skip_serializing_if = "Option::is_none")]
    pub name_match: Option<String>,
    #[serde(rename = "pid", skip_serializing_if = "Option::is_none")]
    pub pid: Option<i32>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(rename = "states", skip_serializing_if = "Option::is_none")]
    pub states: Option<Vec<String>>,
}

impl FindAccessibilityNodesRequest {
    pub fn new() -> FindAccessibilityNodesRequest {
        FindAccessibilityNodesRequest {
            limit: None,
            name: None,
            name_match: None,
            pid: None,
            role: None,
            scope: None,
            states: None,
        }
    }
}
