/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitPeriodGitDeleteBranchRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl GitPeriodGitDeleteBranchRequest {
    pub fn new(name: String, path: String) -> GitPeriodGitDeleteBranchRequest {
        GitPeriodGitDeleteBranchRequest {
            name,
            path,
        }
    }
}

