/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitStatus {
    #[serde(rename = "ahead", skip_serializing_if = "Option::is_none")]
    pub ahead: Option<i32>,
    #[serde(rename = "behind", skip_serializing_if = "Option::is_none")]
    pub behind: Option<i32>,
    #[serde(rename = "branchPublished", skip_serializing_if = "Option::is_none")]
    pub branch_published: Option<bool>,
    #[serde(rename = "currentBranch")]
    pub current_branch: String,
    /// Detached is true when HEAD is not on a branch (detached HEAD state).
    #[serde(rename = "detached", skip_serializing_if = "Option::is_none")]
    pub detached: Option<bool>,
    #[serde(rename = "fileStatus")]
    pub file_status: Vec<models::FileStatus>,
    /// Upstream is the upstream tracking branch (e.g. \"origin/main\"), empty when unset.
    #[serde(rename = "upstream", skip_serializing_if = "Option::is_none")]
    pub upstream: Option<String>,
}

impl GitStatus {
    pub fn new(current_branch: String, file_status: Vec<models::FileStatus>) -> GitStatus {
        GitStatus {
            ahead: None,
            behind: None,
            branch_published: None,
            current_branch,
            detached: None,
            file_status,
            upstream: None,
        }
    }
}
