/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCheckoutRequest {
    #[serde(rename = "branch")]
    pub branch: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl GitCheckoutRequest {
    pub fn new(branch: String, path: String) -> GitCheckoutRequest {
        GitCheckoutRequest {
            branch,
            path,
        }
    }
}

