/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitAddRemoteRequest {
    /// Fetch fetches from the remote immediately after adding it.
    #[serde(rename = "fetch", skip_serializing_if = "Option::is_none")]
    pub fetch: Option<bool>,
    #[serde(rename = "name")]
    pub name: String,
    /// Overwrite replaces an existing remote with the same name.
    #[serde(rename = "overwrite", skip_serializing_if = "Option::is_none")]
    pub overwrite: Option<bool>,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl GitAddRemoteRequest {
    pub fn new(name: String, path: String, url: String) -> GitAddRemoteRequest {
        GitAddRemoteRequest {
            fetch: None,
            name,
            overwrite: None,
            path,
            url,
        }
    }
}
