/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCommitRequest {
    #[serde(rename = "allow_empty", skip_serializing_if = "Option::is_none")]
    pub allow_empty: Option<bool>,
    #[serde(rename = "author")]
    pub author: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl GitCommitRequest {
    pub fn new(author: String, email: String, message: String, path: String) -> GitCommitRequest {
        GitCommitRequest {
            allow_empty: None,
            author,
            email,
            message,
            path,
        }
    }
}
