/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCommitInfo {
    #[serde(rename = "author")]
    pub author: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl GitCommitInfo {
    pub fn new(author: String, email: String, hash: String, message: String, timestamp: String) -> GitCommitInfo {
        GitCommitInfo {
            author,
            email,
            hash,
            message,
            timestamp,
        }
    }
}

