/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterpreterContext {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "language")]
    pub language: String,
}

impl InterpreterContext {
    pub fn new(active: bool, created_at: String, cwd: String, id: String, language: String) -> InterpreterContext {
        InterpreterContext {
            active,
            created_at,
            cwd,
            id,
            language,
        }
    }
}

