/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBranchResponse {
    #[serde(rename = "branches")]
    pub branches: Vec<String>,
}

impl ListBranchResponse {
    pub fn new(branches: Vec<String>) -> ListBranchResponse {
        ListBranchResponse {
            branches,
        }
    }
}

