/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBranchResponse {
    #[serde(rename = "branches")]
    pub branches: Vec<String>,
    /// Current is the name of the checked out branch (empty when HEAD is detached).
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<String>,
}

impl ListBranchResponse {
    pub fn new(branches: Vec<String>) -> ListBranchResponse {
        ListBranchResponse {
            branches,
            current: None,
        }
    }
}
