/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListContextsResponse {
    #[serde(rename = "contexts")]
    pub contexts: Vec<models::InterpreterContext>,
}

impl ListContextsResponse {
    pub fn new(contexts: Vec<models::InterpreterContext>) -> ListContextsResponse {
        ListContextsResponse {
            contexts,
        }
    }
}

