/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspPosition {
    #[serde(rename = "character")]
    pub character: i32,
    #[serde(rename = "line")]
    pub line: i32,
}

impl LspPosition {
    pub fn new(character: i32, line: i32) -> LspPosition {
        LspPosition {
            character,
            line,
        }
    }
}

