/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspRange {
    #[serde(rename = "end")]
    pub end: Box<models::LspPosition>,
    #[serde(rename = "start")]
    pub start: Box<models::LspPosition>,
}

impl LspRange {
    pub fn new(end: models::LspPosition, start: models::LspPosition) -> LspRange {
        LspRange {
            end: Box::new(end),
            start: Box::new(start),
        }
    }
}

