/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspCompletionParams {
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::CompletionContext>>,
    #[serde(rename = "languageId")]
    pub language_id: String,
    #[serde(rename = "pathToProject")]
    pub path_to_project: String,
    #[serde(rename = "position")]
    pub position: Box<models::LspPosition>,
    #[serde(rename = "uri")]
    pub uri: String,
}

impl LspCompletionParams {
    pub fn new(language_id: String, path_to_project: String, position: models::LspPosition, uri: String) -> LspCompletionParams {
        LspCompletionParams {
            context: None,
            language_id,
            path_to_project,
            position: Box::new(position),
            uri,
        }
    }
}

