/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PtyListResponse {
    #[serde(rename = "sessions")]
    pub sessions: Vec<models::PtySessionInfo>,
}

impl PtyListResponse {
    pub fn new(sessions: Vec<models::PtySessionInfo>) -> PtyListResponse {
        PtyListResponse {
            sessions,
        }
    }
}

