/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Recording {
    #[serde(rename = "durationSeconds", skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<f64>,
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "filePath")]
    pub file_path: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sizeBytes", skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<i32>,
    #[serde(rename = "startTime")]
    pub start_time: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl Recording {
    pub fn new(file_name: String, file_path: String, id: String, start_time: String, status: String) -> Recording {
        Recording {
            duration_seconds: None,
            end_time: None,
            file_name,
            file_path,
            id,
            size_bytes: None,
            start_time,
            status,
        }
    }
}

