/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Session {
    #[serde(rename = "commands")]
    pub commands: Vec<models::Command>,
    #[serde(rename = "sessionId")]
    pub session_id: String,
}

impl Session {
    pub fn new(commands: Vec<models::Command>, session_id: String) -> Session {
        Session {
            commands,
            session_id,
        }
    }
}

