/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionExecuteRequest {
    #[serde(rename = "async", skip_serializing_if = "Option::is_none")]
    pub r#async: Option<bool>,
    #[serde(rename = "command")]
    pub command: String,
    #[serde(rename = "runAsync", skip_serializing_if = "Option::is_none")]
    pub run_async: Option<bool>,
    #[serde(rename = "suppressInputEcho", skip_serializing_if = "Option::is_none")]
    pub suppress_input_echo: Option<bool>,
}

impl SessionExecuteRequest {
    pub fn new(command: String) -> SessionExecuteRequest {
        SessionExecuteRequest {
            r#async: None,
            command,
            run_async: None,
            suppress_input_echo: None,
        }
    }
}

