/*
 * Daytona Toolbox API
 *
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Unmodified")]
    Unmodified,
    #[serde(rename = "Untracked")]
    Untracked,
    #[serde(rename = "Modified")]
    Modified,
    #[serde(rename = "Added")]
    Added,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Renamed")]
    Renamed,
    #[serde(rename = "Copied")]
    Copied,
    #[serde(rename = "Updated but unmerged")]
    UpdatedButUnmerged,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl std::fmt::Display for Status {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unmodified => write!(f, "Unmodified"),
            Self::Untracked => write!(f, "Untracked"),
            Self::Modified => write!(f, "Modified"),
            Self::Added => write!(f, "Added"),
            Self::Deleted => write!(f, "Deleted"),
            Self::Renamed => write!(f, "Renamed"),
            Self::Copied => write!(f, "Copied"),
            Self::UpdatedButUnmerged => write!(f, "Updated but unmerged"),
            Self::UnknownDefaultOpenApi => write!(f, "unknown_default_open_api"),
        }
    }
}

impl Default for Status {
    fn default() -> Status {
        Self::Unmodified
    }
}
